import os
import sys
import time
import json
import random
from unittest import mock
import httpx

# Setup path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from app.core.config import settings
from app.core.database import SessionLocal, Base, engine
from app.models.models import Transaction, RecoveryAttempt
from app.services.engine import run_batch

class ResettableRandom:
    def __init__(self):
        self.sequence = [0.1, 0.9, 0.2, 0.8, 0.3, 0.7, 0.4, 0.6, 0.5, 0.15, 0.25, 0.35]
        self.index = 0
    def reset(self):
        self.index = 0
    def __call__(self):
        val = self.sequence[self.index % len(self.sequence)]
        self.index += 1
        return val

def run_performance_test():
    # Initialize clean SQLite DB in memory or temporary file for testing
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    
    # Clean old transactions and attempts
    db.query(RecoveryAttempt).delete()
    db.query(Transaction).delete()
    db.commit()

    print("Seeding test transactions for performance test...")
    # Add 12 dummy failed transactions
    txns = []
    for i in range(12):
        txn = Transaction(
            customer_id=f"cust-{i}",
            amount=100.0 + (i * 50.0),
            failure_code="insufficient_funds",
            raw_failure_text="Declined due to insufficient funds.",
            status="failed",
            attempts_count=0
        )
        db.add(txn)
        txns.append(txn)
    db.commit()

    # We mock LLM call to simulate a realistic network latency of 0.8s
    def mock_post(*args, **kwargs):
        time.sleep(0.8)
        class MockResponse:
            def raise_for_status(self):
                pass
            def json(self):
                return {
                    "choices": [{
                        "message": {
                            "role": "assistant",
                            "content": json.dumps({
                                "category": "insufficient_funds",
                                "confidence": 0.95,
                                "reasoning": "The user has insufficient funds."
                            })
                        }
                    }]
                }
        return MockResponse()

    resettable_rand = ResettableRandom()

    # Use mock patches for httpx.post and random.random
    with mock.patch("httpx.post", side_effect=mock_post), \
         mock.patch("random.random", side_effect=resettable_rand):
        
        # 1. SEQUENTIAL RUN (Workers = 1)
        print("\n--- Running Sequentially (max_workers=1) ---")
        settings.RECOVERY_MAX_WORKERS = 1
        resettable_rand.reset()
        
        # Ensure they are all status="failed"
        for t in txns:
            t.status = "failed"
            t.attempts_count = 0
        db.commit()
        
        start_seq = time.time()
        results_seq = run_batch(db, confidence_threshold=0.7)
        end_seq = time.time()
        seq_time = end_seq - start_seq

        # Record outcomes
        seq_attempts = len(results_seq)
        seq_recovered = sum(1 for r in results_seq if r.outcome == "recovered")
        seq_failed = sum(1 for r in results_seq if r.outcome == "failed")
        seq_escalated = sum(1 for r in results_seq if r.escalated)
        seq_net_recovery = sum(r.net_recovery for r in results_seq if r.net_recovery)

        print(f"Sequential Execution completed in {seq_time:.2f} seconds.")

        # Delete attempts generated by sequential run and reset transactions for parallel run
        db.query(RecoveryAttempt).delete()
        for t in txns:
            t.status = "failed"
            t.attempts_count = 0
        db.commit()

        # 2. PARALLEL RUN (Workers = 4)
        print("\n--- Running in Parallel (max_workers=4) ---")
        settings.RECOVERY_MAX_WORKERS = 4
        resettable_rand.reset()
        
        start_par = time.time()
        results_par = run_batch(db, confidence_threshold=0.7)
        end_par = time.time()
        par_time = end_par - start_par

        # Record outcomes
        par_attempts = len(results_par)
        par_recovered = sum(1 for r in results_par if r.outcome == "recovered")
        par_failed = sum(1 for r in results_par if r.outcome == "failed")
        par_escalated = sum(1 for r in results_par if r.escalated)
        par_net_recovery = sum(r.net_recovery for r in results_par if r.net_recovery)

        print(f"Parallel Execution completed in {par_time:.2f} seconds.")

        # Print detailed side-by-side comparison
        print("\n" + "="*50)
        print("PERFORMANCE & ACCURACY BENCHMARK REPORT")
        print("="*50)
        print(f"Transaction Count:      12")
        print(f"Sequential Runtime:     {seq_time:.3f} s")
        print(f"Parallel Runtime:       {par_time:.3f} s")
        speedup = seq_time / par_time if par_time > 0 else 0
        print(f"Speedup:                {speedup:.2f}x")
        print("-"*50)
        print("Metric                  Sequential      Parallel        Status")
        print("-"*50)
        
        attempts_match = seq_attempts == par_attempts
        rec_match = seq_recovered == par_recovered
        fail_match = seq_failed == par_failed
        esc_match = seq_escalated == par_escalated
        net_match = abs(seq_net_recovery - par_net_recovery) < 0.01

        status = lambda m: "MATCH" if m else "MISMATCH"

        print(f"Total Attempts          {seq_attempts:<16}{par_attempts:<16}{status(attempts_match)}")
        print(f"Recovered Transactions  {seq_recovered:<16}{par_recovered:<16}{status(rec_match)}")
        print(f"Failed Transactions     {seq_failed:<16}{par_failed:<16}{status(fail_match)}")
        print(f"Escalations             {seq_escalated:<16}{par_escalated:<16}{status(esc_match)}")
        print(f"Net Recovery (INR)      {seq_net_recovery:<16.2f}{par_net_recovery:<16.2f}{status(net_match)}")
        print("="*50)

    db.close()

if __name__ == "__main__":
    run_performance_test()
